name: Installing Python

on: [push]

jobs:
  build: 
    runs-on: ${{matrix.os}}
    strategy:
      matrix:
        py-version: [3.10, 3.11, 3.12]
        os: [ubuntu-latest, macos-14, windows-latest]
      
    steps:
    - run: echo "This step runs only if the condition is true."
      if: ${{ matrix.os == '3.1' }}
    - name: Set up Python 
      uses: actions/setup-python@v5
      with:
        python-version: ${{matrix.py-version}}
        





